# Generated by Django 5.2 on 2025-12-26 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('customer_id', models.CharField(db_index=True, help_text='Customer ID from core banking system', max_length=50)),
                ('account_reference', models.CharField(blank=True, help_text='Account number if applicable', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('review_required', 'Review Required')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium-High'), (5, 'Normal'), (7, 'Low'), (10, 'Lowest')], default=5, help_text='Processing priority (1=highest, 10=lowest)')),
                ('customer_data', models.JSONField(default=dict, help_text='Snapshot of customer data from core banking system')),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing began', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall verification score (0-100)', max_digits=5, null=True)),
                ('is_approved', models.BooleanField(help_text='Final approval decision (null = pending)', null=True)),
                ('decision_reason', models.TextField(blank=True, help_text='Explanation for the decision')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from manual review')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Verification officer assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who initiated this verification request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who performed manual review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('field_name', models.CharField(help_text='Name of the field with discrepancy', max_length=100)),
                ('entered_value', models.TextField(help_text='Value as entered in the system')),
                ('document_value', models.TextField(help_text='Value extracted from the document')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Informational')], help_text='Impact level of this discrepancy', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the discrepancy')),
                ('similarity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Similarity score between values (0-100)', max_digits=5)),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('accepted', 'Accepted'), ('corrected', 'Corrected'), ('dismissed', 'Dismissed')], default='unresolved', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='Explanation of how discrepancy was resolved')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text='Parent verification request', on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='verification.verificationrequest')),
            ],
            options={
                'verbose_name': 'Discrepancy',
                'verbose_name_plural': 'Discrepancies',
                'ordering': ['-severity', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('check_type', models.CharField(choices=[('identity', 'Identity Verification'), ('address', 'Address Verification'), ('document', 'Document Authenticity'), ('compliance', 'Regulatory Compliance'), ('policy', 'Policy Compliance')], help_text='Category of verification check', max_length=20)),
                ('check_name', models.CharField(help_text='Specific check identifier', max_length=100)),
                ('score', models.DecimalField(decimal_places=2, help_text='Check score (0-100)', max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='AI confidence level (0-1)', max_digits=5)),
                ('passed', models.BooleanField(help_text='Whether the check passed')),
                ('message', models.TextField(blank=True, help_text='Human-readable result message')),
                ('evidence', models.JSONField(default=dict, help_text='Supporting evidence and raw data')),
                ('request', models.ForeignKey(help_text='Parent verification request', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='verification.verificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Result',
                'verbose_name_plural': 'Verification Results',
                'ordering': ['check_type', 'check_name'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['customer_id', 'status'], name='verificatio_custome_ff2728_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status', 'priority'], name='verificatio_status_d7a5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='verificatio_assigne_60a86b_idx'),
        ),
    ]
