# Generated by Django 5.2 on 2025-12-26 09:16

import apps.documents.models.document
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('application_form', 'Application Form'), ('signature_card', 'Signature Card'), ('photo', 'Photograph'), ('other', 'Other')], help_text='Type of document', max_length=30)),
                ('file', models.FileField(help_text='Uploaded document file', upload_to=apps.documents.models.document.document_upload_path)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether OCR processing is complete')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('page_count', models.IntegerField(default=1, help_text='Number of pages in the document')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Document quality score (0-100)', max_digits=5, null=True)),
                ('verification_request', models.ForeignKey(help_text='Related verification request', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.verificationrequest')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('raw_text', models.TextField(blank=True, help_text='Full text extracted from document')),
                ('structured_data', models.JSONField(default=dict, help_text='Parsed field values (e.g., name, id_number, etc.)')),
                ('confidence_scores', models.JSONField(default=dict, help_text='Confidence score for each extracted field')),
                ('extraction_method', models.CharField(choices=[('ocr', 'OCR'), ('ai', 'AI/LLM'), ('manual', 'Manual Entry')], default='ocr', max_length=20)),
                ('model_version', models.CharField(blank=True, help_text='Version of OCR/AI model used', max_length=50)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('overall_confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall extraction confidence (0-1)', max_digits=5)),
                ('document', models.ForeignKey(help_text='Source document', on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Extraction',
                'verbose_name_plural': 'Document Extractions',
                'ordering': ['-created_at'],
            },
        ),
    ]
