# Generated by Django 5.2 on 2025-12-26 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('name', models.CharField(help_text='Rule name', max_length=200)),
                ('code', models.CharField(help_text='Unique rule code within policy', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('rule_type', models.CharField(choices=[('required_document', 'Required Document'), ('field_validation', 'Field Validation'), ('threshold', 'Threshold Check'), ('watchlist', 'Watchlist Check'), ('age_verification', 'Age Verification'), ('custom', 'Custom Rule')], help_text='Type of rule', max_length=30)),
                ('condition', models.JSONField(default=dict, help_text='Rule condition definition (JSON)')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Importance weight for scoring', max_digits=5)),
                ('is_blocking', models.BooleanField(default=False, help_text='Whether failure blocks approval')),
                ('error_message', models.TextField(blank=True, help_text='Message to display when rule fails')),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'ordering': ['-is_blocking', '-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('name', models.CharField(help_text='Policy name', max_length=200)),
                ('code', models.CharField(help_text='Unique policy code', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('kyc', 'Know Your Customer'), ('aml', 'Anti-Money Laundering'), ('institutional', 'Institutional Policy'), ('regulatory', 'Regulatory Requirement')], help_text='Policy category', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Brief description of the policy')),
                ('content', models.TextField(help_text='Full policy text')),
                ('version', models.CharField(default='1.0', help_text='Policy version', max_length=20)),
                ('effective_date', models.DateField(help_text='When this policy takes effect')),
                ('expiry_date', models.DateField(blank=True, help_text='When this policy expires (if applicable)', null=True)),
                ('embedding_id', models.CharField(blank=True, help_text='ID in ChromaDB for semantic search', max_length=100)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('passed', models.BooleanField(help_text='Whether the check passed')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Compliance score (0-100)', max_digits=5)),
                ('details', models.JSONField(default=dict, help_text='Detailed evaluation results')),
                ('message', models.TextField(blank=True, help_text='Human-readable result message')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='When the check was performed')),
                ('verification_request', models.ForeignKey(help_text='Related verification request', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='verification.verificationrequest')),
                ('rule', models.ForeignKey(help_text='Rule that was evaluated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='compliance.compliancerule')),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'verbose_name_plural': 'Compliance Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='compliancerule',
            name='policy',
            field=models.ForeignKey(help_text='Parent policy', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='compliance.policy'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancerule',
            unique_together={('policy', 'code')},
        ),
    ]
